version: '3.9'

services:
  #MongoDB services
  mongo_db:
    container_name: db_container1
    image: mongo:latest
    restart: always
    ports:
    - 2717:27017 
    volumes:
    - mongo_db:/data/db

#Node API service
  api:
    build: .
    ports:
     - 8080:8080
    volumes:
     - .:/app1
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://127.0.0.1:27017
    depends_on:
     - mongo_db

volumes:
  mongo_db: {}  